name = "KernelDensitySJ"
uuid = "49dc5b4e-6806-4504-b2cc-a81764e7a38b"
version = "0.2.2"
authors = ["Rasmus Henningsson <rasmus.henningsson@gmail.com>", "Lund University"]

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DataStructures = "0.17, 0.18, 0.19"
Roots = "1, 2"
Statistics = "1"
julia = "1"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Distributions", "StableRNGs"]
